spring:
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
  datasource:
    url: jdbc:postgresql://localhost:5432/stuff
    username: postgres
    password: example
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: "localhost:29092,localhost:39092"
    consumer:
      group-id: "zettle_group"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
